name: Build artifacts and push to gh-pages
on:
  #pull_request_target:
  #  types: [closed]
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  # Build the website and create artifacts
  build_and_create_artifact:
    name: Build and create artifacts
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the website
      - name: Build npm commands
        run: |
          npm install
          npm run build --if-present

      # Push to the gh-pages branch
      - name: Push to gh-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: toto # The branch name where you want to push the assets
          FOLDER: dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
