name: Build artifacts and push to gh-pages
on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_call:

jobs:
  # Build the website and create artifacts
  build_and_create_artifact:
    name: Build and create artifacts
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: write
      packages: write
      statuses: write
      actions: write
      checks: read
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the website
      - name: Build npm commands
        run: |
          npm install
          npm run build --if-present

      # Push to the gh-pages branch
      - name: Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch name where you want to push the assets
          folder: dist # The directory where your assets are generated
          ssh-key: ${{ secrets.PUSH-GH-PAGES }}
          single-commit: true
